"""
Django settings for bengkel_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# =====================================
# BASIC SETTINGS
# =====================================
SECRET_KEY = os.getenv('SECRET_KEY', 'fallback-key')
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = ['*']  # allow all for docker / LAN


# =====================================
# INSTALLED APPS
# =====================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'django_extensions',
    'debug_toolbar',

    # Local apps
    'apps.accounts',
    'apps.dashboard',
    'apps.transactions.apps.TransactionsConfig',
    'apps.inventory',
    'apps.master_data',
    'apps.expenses',
    'apps.purchases.apps.PurchasesConfig',
    'apps.reports',
]


# =====================================
# MIDDLEWARE
# =====================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Debug Toolbar (harus paling bawah)
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]


ROOT_URLCONF = 'bengkel_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bengkel_project.wsgi.application'


# =====================================
# DATABASE
# =====================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', 5432),
    }
}


# =====================================
# PASSWORD VALIDATION
# =====================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =====================================
# INTERNATIONALIZATION
# =====================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True


# =====================================
# STATIC & MEDIA (Docker Friendly)
# =====================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']   # dev mode
STATIC_ROOT = BASE_DIR / 'staticfiles'     # collected in docker production

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =====================================
# CRISPY FORMS
# =====================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# =====================================
# DEBUG TOOLBAR (Fix Docker)
# =====================================
INTERNAL_IPS = [
    "127.0.0.1",
    "0.0.0.0",
]

# Fix Debug Toolbar in Docker
import socket
try:
    INTERNAL_IPS += [socket.gethostbyname(socket.gethostname())]
except:
    pass


# =====================================
# CUSTOM USER MODEL
# =====================================
AUTH_USER_MODEL = 'accounts.CustomUser'


# =====================================
# LOGIN SETTINGS
# =====================================
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:index'
LOGOUT_REDIRECT_URL = 'accounts:login'


# =====================================
# ESC/POS SETTINGS (USB)
# =====================================
ESC_POS_PRINTER = {
    'VID': 0x0483,
    'PID': 0x070b,
}
