services:
  web:
    build: .
    user: "${UID}:${GID}"
    # Command for development. For production, we'll use gunicorn.
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      # Expose on 5433 to avoid conflict with local postgres
      - "5433:5432"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: