version: '3.8'

services:
  web:
    build: .
    user: "${UID}:${GID}"
    # Ganti gunicorn dengan runserver
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Akses via http://localhost:8000 atau http://<IP_LAPTOP>:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"  # Expose on 5433 to avoid conflict with local postgres

volumes:
  postgres_data: