# Generated by Django 5.2.6 on 2025-09-06 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Pembuatan'), ('UPDATE', 'Pembaruan'), ('DELETE', 'Penghapusan'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TRX_COMPLETE', 'Transaksi Selesai')], help_text='Jenis aksi yang dilakukan.', max_length=20)),
                ('action_details', models.TextField(help_text='Deskripsi detail dari aksi yang dilakukan.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(help_text='Pengguna yang melakukan aksi.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
