# Generated by Django 4.2.11 on 2026-02-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Status Aktif"),
        ),
    ]
