# Generated by Django 4.2.11 on 2026-02-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_vehicle_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="is_active",
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Status Aktif"),
        ),
    ]
