# Generated by Django 4.2.11 on 2026-02-03 07:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="other_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Biaya tambahan lain-lain (Global)",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="TransactionMisc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Nama barang/biaya", max_length=255),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miscs",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
    ]
