# Generated by Django 5.2.7 on 2025-10-09 11:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionservice",
            old_name="price",
            new_name="unit_price",
        ),
        migrations.AddField(
            model_name="transactionservice",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Potongan harga final",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="other_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Biaya lain-lain",
                max_digits=12,
            ),
        ),
    ]
