# Generated by Django 4.2.11 on 2026-01-16 03:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Diskon final (Nominal Rupiah)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Catatan keluhan atau perbaikan"
            ),
        ),
    ]
