# Generated by Django 4.2.11 on 2026-02-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_other_charges_transactionmisc"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="include_install",
            field=models.BooleanField(
                default=True, help_text="Apakah termasuk biaya pasang?"
            ),
        ),
    ]
