# Generated by Django 4.2.11 on 2026-02-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_inventoryitem_install_price_and_more"),
        ("transactions", "0003_transactionitem_include_install"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionitem",
            name="include_install",
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="install_service",
            field=models.ForeignKey(
                blank=True,
                help_text="Pilihan harga jasa pasang (opsional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.vehicleserviceprice",
            ),
        ),
    ]
