# Generated by Django 5.2.6 on 2025-09-06 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PergerakanStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('MASUK', 'Stok Masuk (Pembelian)'), ('KELUAR', 'Stok Keluar (Penjualan)'), ('KOREKSI', 'Koreksi Stok')], max_length=10)),
                ('jumlah', models.IntegerField()),
                ('harga_beli_satuan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Pergerakan Stok',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255, unique=True)),
                ('tipe', models.CharField(choices=[('sparepart', 'Sparepart (Habis Pakai)'), ('tools', 'Alat (Tidak Habis Pakai)')], max_length=20)),
                ('kode_produk', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('ambang_batas_stok', models.PositiveIntegerField(default=5)),
                ('harga_jual_standar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama_produk'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
                ('kontak', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='TipePembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipe Pembelian',
                'ordering': ['nama'],
            },
        ),
    ]
