# Generated by Django 5.2.6 on 2025-09-06 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pergerakanstok',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.kategori'),
        ),
        migrations.AddField(
            model_name='produk',
            name='merek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.merek'),
        ),
        migrations.AddField(
            model_name='pergerakanstok',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pergerakan', to='inventory.produk'),
        ),
        migrations.AddField(
            model_name='pergerakanstok',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='pergerakanstok',
            name='tipe_pembelian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tipepembelian'),
        ),
    ]
