# Generated by Django 5.2.6 on 2025-09-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.CharField(editable=False, max_length=20, unique=True)),
                ('jenis_service', models.CharField(choices=[('rutin', 'Service Rutin'), ('perbaikan', 'Perbaikan'), ('ganti_oli', 'Ganti Oli'), ('lainnya', 'Lainnya')], default='rutin', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('biaya_jasa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rating_customer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('komentar_customer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_digunakan', models.PositiveIntegerField(default=1)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Produk Transaksi',
            },
        ),
    ]
