# Generated by Django 5.2.6 on 2025-09-06 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_set', to='users.customer'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='montir',
            field=models.ForeignKey(limit_choices_to={'role': 'montir'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_montir_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaksiproduk',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produk'),
        ),
        migrations.AddField(
            model_name='transaksiproduk',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaksi'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='spareparts',
            field=models.ManyToManyField(related_name='transaksi_set', through='transactions.TransaksiProduk', to='inventory.produk'),
        ),
        migrations.AlterUniqueTogether(
            name='transaksiproduk',
            unique_together={('transaksi', 'produk')},
        ),
    ]
