# Generated by Django 4.2.11 on 2026-02-09 05:21

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="install_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Biaya jasa pasang standar untuk barang ini (opsional)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="sell_price",
            field=models.DecimalField(
                decimal_places=2, help_text="Harga jual barang saja", max_digits=10
            ),
        ),
    ]
