# Generated by Django 4.2.11 on 2026-01-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="extra_specs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Data dinamis (JSON)"
            ),
        ),
    ]
