# Generated by Django 4.2.11 on 2026-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_extra_specs"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="required_specs",
            field=models.CharField(
                blank=True,
                help_text="Masukkan nama spesifikasi dipisahkan koma. Contoh: Volume, SAE, Type",
                max_length=500,
            ),
        ),
    ]
