# Generated by Django 4.2.11 on 2026-02-09 10:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_inventoryitem_created_at_inventoryitem_install_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="install_service_name",
            field=models.CharField(
                default="Jasa Pasang",
                help_text="Nama layanan untuk biaya pasang ini (contoh: Pasang Ban, Pasang Aki)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Tanggal Masuk"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="install_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Biaya jasa pasang standar (umum).",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="VehicleServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        help_text="Contoh: NMAX, Beat, Sport 150cc", max_length=100
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_prices",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
