# Generated by Django 4.2.11 on 2026-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_alter_category_options_alter_inventoryitem_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="install_price",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="install_service_name",
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="vehicleserviceprice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Harga jasa pasang", max_digits=10
            ),
        ),
    ]
