# Generated by Django 4.2.11 on 2026-01-15 10:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_category_required_specs"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Jika tidak dicentang, kategori ini akan disembunyikan.",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Jika Non-Aktif, item tidak akan muncul di list penjualan.",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="buy_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="extra_specs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_threshold",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="sell_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
