# Generated by Django 4.2.11 on 2026-01-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_category_is_active_inventoryitem_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="extra_specs",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
