# Generated by Django 5.2.8 on 2025-11-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="purchaser_custom",
            field=models.CharField(
                blank=True,
                help_text="Isi manual jika yang belanja bukan Montir terdaftar",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="purchaser_mechanic",
            field=models.ForeignKey(
                blank=True,
                help_text="Pilih jika yang belanja adalah Montir",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master_data.mechanic",
            ),
        ),
    ]
