# Generated by Django 4.2.11 on 2025-12-04 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-due_date"]},
        ),
        migrations.RemoveField(
            model_name="expense",
            name="date",
        ),
        migrations.AddField(
            model_name="expense",
            name="due_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Tanggal jatuh tempo"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_date",
            field=models.DateField(
                blank=True, help_text="Tanggal pembayaran real", null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Belum Dibayar (Hutang)"),
                    ("PAID", "Sudah Dibayar (Lunas)"),
                ],
                default="PAID",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default="Pengeluaran", max_length=200),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Contoh: Gaji Miko", max_length=200),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "due_date_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Tanggal jatuh tempo setiap bulan (misal: 25)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Matikan jika karyawan resign atau layanan berhenti",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="expenses.expensecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="recurring_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="expenses.recurringexpense",
            ),
        ),
    ]
